jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 1. Instalar Node.js
            if ! command -v npm &>/dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # 2. Preparar directorio y clonar repo
            mkdir -p /var/www/html/Suncodex_Admin
            cd /var/www/html/Suncodex_Admin
            
            if ! git rev-parse --is-inside-work-tree &>/dev/null; then
              git clone https://github.com/TU_USUARIO/TU_REPO.git .
            fi
            
            # 3. Despliegue
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            npm install
            ng build --configuration production
