name: Deploy Angular to Server

on:
  push:
    branches:
      - master  
  workflow_dispatch:  
  jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Angular via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if ! command -v node &>/dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            if ! command -v ng &>/dev/null || [[ $(ng version | grep 'Angular CLI' | awk '{print $3}') != "19.2.9" ]]; then
              sudo npm install -g @angular/cli@19.2.9
            fi

            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            cd ${{ secrets.WORK_DIR }} 
            git fetch 
            git checkout ${{ secrets.MAIN_BRANCH }} 
            git pull 
            npm install 
            ng build --configuration production
            exit