name: Build and Deploy Angular

on:
  push:
    branches: [ master ]  # Cambia según tu rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'  # Usa tu versión

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: |
          npm install -g @angular/cli@19.2.9  # Ajusta la versión
          ng build --configuration production

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/admin/browser/*"  # Ajusta según tu angular.json > outputPath
          target: "/var/www/html/Suncodex_Admin"
          rm: true  # Borra archivos antiguos en el servidor

      - name: Restart Nginx (Opcional)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart nginx